//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS3.FEMTools.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:soap", ConfigurationName="ServiceReference.soapPort")]
    public interface soapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:soap#Service#sayHello", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sayHello")]
        string sayHello(string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:soap#Service#sayHello", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sayHello")]
        System.Threading.Tasks.Task<string> sayHelloAsync(string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:soap#Service#add", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="add")]
        string add(string a, string b);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:soap#Service#add", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="add")]
        System.Threading.Tasks.Task<string> addAsync(string a, string b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface soapPortChannel : IS3.FEMTools.ServiceReference.soapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class soapPortClient : System.ServiceModel.ClientBase<IS3.FEMTools.ServiceReference.soapPort>, IS3.FEMTools.ServiceReference.soapPort {
        
        public soapPortClient() {
        }
        
        public soapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public soapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public soapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public soapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sayHello(string content) {
            return base.Channel.sayHello(content);
        }
        
        public System.Threading.Tasks.Task<string> sayHelloAsync(string content) {
            return base.Channel.sayHelloAsync(content);
        }
        
        public string add(string a, string b) {
            return base.Channel.add(a, b);
        }
        
        public System.Threading.Tasks.Task<string> addAsync(string a, string b) {
            return base.Channel.addAsync(a, b);
        }
    }
}
